export default [
  { id: 1, key: "Esc" },
  { id: 2, key: "`", subKey: "~" },
  { id: 3, key: "1", subKey: "!" },
  { id: 4, key: "2", subKey: "@" },
  { id: 5, key: "3", subKey: "#" },
  { id: 6, key: "4", subKey: "$" },
  { id: 7, key: "5", subKey: "%" },
  { id: 8, key: "6", subKey: "^" },
  { id: 9, key: "7", subKey: "&" },
  { id: 10, key: "8", subKey: "*" },
  { id: 11, key: "9", subKey: "(" },
  { id: 12, key: "0", subKey: ")" },
  { id: 13, key: "-", subKey: "_" },
  { id: 14, key: "Back" },
  { id: 15, key: "Tab" },
  { id: 16, key: "Q" },
  { id: 17, key: "W" },
  { id: 18, key: "E" },
  { id: 20, key: "R" },
  { id: 21, key: "T" },
  { id: 22, key: "Y" },
  { id: 23, key: "U" },
  { id: 24, key: "I" },
  { id: 25, key: "O" },
  { id: 26, key: "P" },
  { id: 27, key: "[", subKey: "{" },
  { id: 28, key: "]", subKey: "}" },
  { id: 29, key: "\\", subKey: "|" },
  { id: 30, key: "Caps", isModifierKey: true },
  { id: 31, key: "A" },
  { id: 32, key: "S" },
  { id: 33, key: "D" },
  { id: 34, key: "F" },
  { id: 35, key: "G" },
  { id: 36, key: "H" },
  { id: 37, key: "I" },
  { id: 38, key: "J" },
  { id: 39, key: "K" },
  { id: 40, key: "L" },
  { id: 41, key: ";", subKey: ":" },
  { id: 42, key: "'", subKey: `"` },
  { id: 43, key: "Enter", isModifierKey: true },
  { id: 44, key: "Shift", isModifierKey: true },
  { id: 45, key: "Z" },
  { id: 46, key: "X" },
  { id: 47, key: "C" },
  { id: 48, key: "V" },
  { id: 49, key: "B" },
  { id: 50, key: "N" },
  { id: 51, key: "M" },
  { id: 52, key: ",", subKey: "<" },
  { id: 53, key: ".", subKey: ">" },
  { id: 54, key: "/", subKey: "?" },
  { id: 55, key: "UP" },
  { id: 56, key: "Shift", isModifierKey: true },
  { id: 57, key: "Ctrl", isModifierKey: true },
  { id: 58, key: "Mod", isModifierKey: true },
  { id: 59, key: "Alt", isModifierKey: true },
  { id: 60, key: "Space" },
  { id: 61, key: "Alt", isModifierKey: true },
  { id: 62, key: "LEFT" },
  { id: 63, key: "DOWN" },
  { id: 64, key: "RIGHT" },
  { id: 65, key: "Ctrl", isModifierKey: true },
];
