export default [
  { key: "Esc" },
  { key: "`", subKey: "~" },
  { key: "1", subKey: "!" },
  { key: "2", subKey: "@" },
  { key: "3", subKey: "#" },
  { key: "4", subKey: "$" },
  { key: "5", subKey: "%" },
  { key: "6", subKey: "^" },
  { key: "7", subKey: "&" },
  { key: "8", subKey: "*" },
  { key: "9", subKey: "(" },
  { key: "0", subKey: ")" },
  { key: "-", subKey: "_" },
  { key: "Back" },
  { key: "Tab" },
  { key: "Q" },
  { key: "W" },
  { key: "E" },
  { key: "R" },
  { key: "T" },
  { key: "Y" },
  { key: "U" },
  { key: "I" },
  { key: "O" },
  { key: "P" },
  { key: "[", subKey: "{" },
  { key: "]", subKey: "}" },
  { key: "\\", subKey: "|" },
  { key: "Caps" },
  { key: "A" },
  { key: "S" },
  { key: "D" },
  { key: "F" },
  { key: "G" },
  { key: "H" },
  { key: "I" },
  { key: "J" },
  { key: "K" },
  { key: "L" },
  { key: ";", subKey: ":" },
  { key: "'", subKey: `"` },
  { key: "Enter" },
  { key: "Shift" },
  { key: "Z" },
  { key: "X" },
  { key: "C" },
  { key: "V" },
  { key: "B" },
  { key: "N" },
  { key: "M" },
  { key: ",", subKey: "<" },
  { key: ".", subKey: ">" },
  { key: "/", subKey: "?" },
  { key: "UP" },
  { key: "Shift2" },
  { key: "Ctrl" },
  { key: "Mod" },
  { key: "Alt" },
  { key: "Space" },
  { key: "Alt" },
  { key: "LEFT" },
  { key: "DOWN" },
  { key: "RIGHT" },
  { key: "Ctrl2" },
];
